# kafka consumer settings
bootstrap.servers=localhost:9092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
acks=all
group.id="kafka-consumer"

topic.name=transactions-topic