# kafka consumer settings
bootstrap.servers=localhost:9092
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=sbp.school.kafka.utils.TransactionDeserializer
acks=all
group.id=transaction-consumer-group
enable.auto.commit=false
auto.offset.reset=earliest
max.poll.records=500

# Topic name
topic.name=trans-topic